/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Album {
  'title' : string,
  'tracks' : Array<string>,
  'releaseDate' : Time,
}
export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
  'image' : [] | [ExternalBlob],
  'archived' : boolean,
}
export interface Comment {
  'id' : bigint,
  'contentId' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'archived' : boolean,
}
export interface CreateArticleRequest {
  'title' : string,
  'content' : string,
  'image' : [] | [ExternalBlob],
}
export interface CreateDiscussionRequest {
  'title' : string,
  'content' : string,
  'category' : string,
}
export interface CreateRumorRequest {
  'status' : Status,
  'title' : string,
  'content' : string,
}
export interface Discography {
  'albums' : Array<Album>,
  'singles' : Array<Single>,
}
export interface Discussion {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'category' : string,
  'archived' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface Group {
  'schedules' : Array<Schedule>,
  'members' : Array<Member>,
  'discography' : Discography,
  'name' : string,
  'news' : Array<GroupNews>,
  'memberCount' : bigint,
  'baseLocation' : string,
  'formationDate' : Time,
  'setlists' : Array<Setlist>,
  'theaterLocation' : string,
}
export interface GroupNews {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
}
export interface HomepageContent {
  'latestArticlesTable' : Array<LatestArticleTable>,
  'rumors' : Array<Rumor>,
  'articles' : Array<Article>,
  'trending' : Array<Trending>,
  'discussions' : Array<Discussion>,
  'trendingTable' : Array<TrendingTable>,
}
export interface LatestArticleTable {
  'itemId' : bigint,
  'itemType' : string,
  'uploadDate' : Time,
}
export interface Member {
  'bio' : string,
  'nickname' : string,
  'birthdate' : Time,
  'team' : string,
  'generation' : string,
  'fullName' : string,
}
export interface Rumor {
  'id' : bigint,
  'status' : Status,
  'title' : string,
  'content' : string,
  'date' : Time,
  'archived' : boolean,
}
export interface Schedule {
  'date' : Time,
  'event' : string,
  'location' : string,
}
export interface Setlist { 'title' : string, 'tracks' : Array<string> }
export interface Single {
  'title' : string,
  'tracks' : Array<string>,
  'releaseDate' : Time,
}
export type Status = { 'unconfirm' : null } |
  { 'confirm' : null } |
  { 'waiting' : null };
export type Time = bigint;
export interface Trending {
  'id' : bigint,
  'contentId' : bigint,
  'contentType' : string,
  'timestamp' : Time,
}
export interface TrendingTable {
  'itemId' : bigint,
  'timestamp' : Time,
  'itemType' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'addTrending' : ActorMethod<[bigint, string], bigint>,
  'archiveArticle' : ActorMethod<[bigint], undefined>,
  'archiveComment' : ActorMethod<[bigint], undefined>,
  'archiveDiscussion' : ActorMethod<[bigint], undefined>,
  'archiveRumor' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<[CreateArticleRequest], bigint>,
  'createDiscussion' : ActorMethod<[CreateDiscussionRequest], bigint>,
  'createGroup' : ActorMethod<[Group], undefined>,
  'createRumor' : ActorMethod<[CreateRumorRequest], bigint>,
  'deleteGroup' : ActorMethod<[string], undefined>,
  'filterArticlesByTitle' : ActorMethod<[string], Array<Article>>,
  'filterDiscussionsByCategory' : ActorMethod<[string], Array<Discussion>>,
  'filterRumorsByStatus' : ActorMethod<[Status], Array<Rumor>>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllComments' : ActorMethod<[], Array<Comment>>,
  'getAllDiscussions' : ActorMethod<[], Array<Discussion>>,
  'getAllGroups' : ActorMethod<[], Array<Group>>,
  'getAllRumors' : ActorMethod<[], Array<Rumor>>,
  'getAllTrending' : ActorMethod<[], Array<Trending>>,
  'getArticle' : ActorMethod<[bigint], Article>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComment' : ActorMethod<[bigint], Comment>,
  'getCommentsByContentId' : ActorMethod<[bigint], Array<Comment>>,
  'getDiscussion' : ActorMethod<[bigint], Discussion>,
  'getGroup' : ActorMethod<[string], Group>,
  'getHomepageContent' : ActorMethod<[], HomepageContent>,
  'getRumor' : ActorMethod<[bigint], Rumor>,
  'getTrending' : ActorMethod<[bigint], Trending>,
  'getUnarchivedArticles' : ActorMethod<[], Array<Article>>,
  'getUnarchivedComments' : ActorMethod<[], Array<Comment>>,
  'getUnarchivedDiscussions' : ActorMethod<[], Array<Discussion>>,
  'getUnarchivedRumors' : ActorMethod<[], Array<Rumor>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeTrending' : ActorMethod<[bigint], undefined>,
  'restoreArticle' : ActorMethod<[bigint], undefined>,
  'restoreComment' : ActorMethod<[bigint], undefined>,
  'restoreDiscussion' : ActorMethod<[bigint], undefined>,
  'restoreRumor' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateArticle' : ActorMethod<
    [bigint, string, [] | [ExternalBlob], string],
    undefined
  >,
  'updateComment' : ActorMethod<[bigint, string], undefined>,
  'updateDiscussion' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateGroup' : ActorMethod<[Group], undefined>,
  'updateRumor' : ActorMethod<[bigint, string, string, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];