/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateArticleRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const CreateDiscussionRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const ScheduleWithGroup = IDL.Record({
  'date' : Time,
  'event' : IDL.Text,
  'groupName' : IDL.Text,
  'location' : IDL.Text,
});
export const Member = IDL.Record({
  'bio' : IDL.Text,
  'nickname' : IDL.Text,
  'birthdate' : Time,
  'team' : IDL.Text,
  'generation' : IDL.Text,
  'fullName' : IDL.Text,
});
export const Album = IDL.Record({
  'title' : IDL.Text,
  'tracks' : IDL.Vec(IDL.Text),
  'releaseDate' : Time,
});
export const Single = IDL.Record({
  'title' : IDL.Text,
  'tracks' : IDL.Vec(IDL.Text),
  'releaseDate' : Time,
});
export const Discography = IDL.Record({
  'albums' : IDL.Vec(Album),
  'singles' : IDL.Vec(Single),
});
export const GroupNews = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
});
export const Setlist = IDL.Record({
  'title' : IDL.Text,
  'tracks' : IDL.Vec(IDL.Text),
});
export const Group = IDL.Record({
  'schedules' : IDL.Vec(ScheduleWithGroup),
  'active' : IDL.Bool,
  'members' : IDL.Vec(Member),
  'discography' : Discography,
  'name' : IDL.Text,
  'news' : IDL.Vec(GroupNews),
  'memberCount' : IDL.Nat,
  'baseLocation' : IDL.Text,
  'formationDate' : Time,
  'setlists' : IDL.Vec(Setlist),
  'theaterLocation' : IDL.Text,
});
export const Status = IDL.Variant({
  'unconfirm' : IDL.Null,
  'confirm' : IDL.Null,
  'waiting' : IDL.Null,
});
export const CreateRumorRequest = IDL.Record({
  'status' : Status,
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'archived' : IDL.Bool,
});
export const Discussion = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'category' : IDL.Text,
  'archived' : IDL.Bool,
});
export const Rumor = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'archived' : IDL.Bool,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'contentId' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'archived' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'archiveArticle' : IDL.Func([IDL.Nat], [], []),
  'archiveComment' : IDL.Func([IDL.Nat], [], []),
  'archiveDiscussion' : IDL.Func([IDL.Nat], [], []),
  'archiveRumor' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func([CreateArticleRequest], [IDL.Nat], []),
  'createDiscussion' : IDL.Func([CreateDiscussionRequest], [IDL.Nat], []),
  'createGroup' : IDL.Func([Group], [], []),
  'createRumor' : IDL.Func([CreateRumorRequest], [IDL.Nat], []),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteDiscussion' : IDL.Func([IDL.Nat], [], []),
  'deleteGroup' : IDL.Func([IDL.Text], [], []),
  'deleteRumor' : IDL.Func([IDL.Nat], [], []),
  'filterArticlesByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'filterDiscussionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Discussion)],
      ['query'],
    ),
  'filterRumorsByStatus' : IDL.Func([Status], [IDL.Vec(Rumor)], ['query']),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getAllDiscussions' : IDL.Func([], [IDL.Vec(Discussion)], ['query']),
  'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getAllRumors' : IDL.Func([], [IDL.Vec(Rumor)], ['query']),
  'getAllUpcomingEvents' : IDL.Func(
      [],
      [IDL.Vec(ScheduleWithGroup)],
      ['query'],
    ),
  'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComment' : IDL.Func([IDL.Nat], [Comment], ['query']),
  'getCommentsByContentId' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getDiscussion' : IDL.Func([IDL.Nat], [Discussion], ['query']),
  'getGroup' : IDL.Func([IDL.Text], [Group], ['query']),
  'getRumor' : IDL.Func([IDL.Nat], [Rumor], ['query']),
  'getUnarchivedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getUnarchivedComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getUnarchivedDiscussions' : IDL.Func([], [IDL.Vec(Discussion)], ['query']),
  'getUnarchivedRumors' : IDL.Func([], [IDL.Vec(Rumor)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'renameGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'restoreArticle' : IDL.Func([IDL.Nat], [], []),
  'restoreComment' : IDL.Func([IDL.Nat], [], []),
  'restoreDiscussion' : IDL.Func([IDL.Nat], [], []),
  'restoreRumor' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchContent' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'members' : IDL.Vec(Member),
          'groups' : IDL.Vec(Group),
          'rumors' : IDL.Vec(Rumor),
          'articles' : IDL.Vec(Article),
          'discussions' : IDL.Vec(Discussion),
        }),
      ],
      ['query'],
    ),
  'updateArticle' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateDiscussion' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateGroup' : IDL.Func([Group], [], []),
  'updateRumor' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Status], [], []),
  'updateRumorStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateArticleRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const CreateDiscussionRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const ScheduleWithGroup = IDL.Record({
    'date' : Time,
    'event' : IDL.Text,
    'groupName' : IDL.Text,
    'location' : IDL.Text,
  });
  const Member = IDL.Record({
    'bio' : IDL.Text,
    'nickname' : IDL.Text,
    'birthdate' : Time,
    'team' : IDL.Text,
    'generation' : IDL.Text,
    'fullName' : IDL.Text,
  });
  const Album = IDL.Record({
    'title' : IDL.Text,
    'tracks' : IDL.Vec(IDL.Text),
    'releaseDate' : Time,
  });
  const Single = IDL.Record({
    'title' : IDL.Text,
    'tracks' : IDL.Vec(IDL.Text),
    'releaseDate' : Time,
  });
  const Discography = IDL.Record({
    'albums' : IDL.Vec(Album),
    'singles' : IDL.Vec(Single),
  });
  const GroupNews = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
  });
  const Setlist = IDL.Record({
    'title' : IDL.Text,
    'tracks' : IDL.Vec(IDL.Text),
  });
  const Group = IDL.Record({
    'schedules' : IDL.Vec(ScheduleWithGroup),
    'active' : IDL.Bool,
    'members' : IDL.Vec(Member),
    'discography' : Discography,
    'name' : IDL.Text,
    'news' : IDL.Vec(GroupNews),
    'memberCount' : IDL.Nat,
    'baseLocation' : IDL.Text,
    'formationDate' : Time,
    'setlists' : IDL.Vec(Setlist),
    'theaterLocation' : IDL.Text,
  });
  const Status = IDL.Variant({
    'unconfirm' : IDL.Null,
    'confirm' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const CreateRumorRequest = IDL.Record({
    'status' : Status,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'archived' : IDL.Bool,
  });
  const Discussion = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'category' : IDL.Text,
    'archived' : IDL.Bool,
  });
  const Rumor = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'archived' : IDL.Bool,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'contentId' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'archived' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'archiveArticle' : IDL.Func([IDL.Nat], [], []),
    'archiveComment' : IDL.Func([IDL.Nat], [], []),
    'archiveDiscussion' : IDL.Func([IDL.Nat], [], []),
    'archiveRumor' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func([CreateArticleRequest], [IDL.Nat], []),
    'createDiscussion' : IDL.Func([CreateDiscussionRequest], [IDL.Nat], []),
    'createGroup' : IDL.Func([Group], [], []),
    'createRumor' : IDL.Func([CreateRumorRequest], [IDL.Nat], []),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteDiscussion' : IDL.Func([IDL.Nat], [], []),
    'deleteGroup' : IDL.Func([IDL.Text], [], []),
    'deleteRumor' : IDL.Func([IDL.Nat], [], []),
    'filterArticlesByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'filterDiscussionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Discussion)],
        ['query'],
      ),
    'filterRumorsByStatus' : IDL.Func([Status], [IDL.Vec(Rumor)], ['query']),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getAllDiscussions' : IDL.Func([], [IDL.Vec(Discussion)], ['query']),
    'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getAllRumors' : IDL.Func([], [IDL.Vec(Rumor)], ['query']),
    'getAllUpcomingEvents' : IDL.Func(
        [],
        [IDL.Vec(ScheduleWithGroup)],
        ['query'],
      ),
    'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComment' : IDL.Func([IDL.Nat], [Comment], ['query']),
    'getCommentsByContentId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getDiscussion' : IDL.Func([IDL.Nat], [Discussion], ['query']),
    'getGroup' : IDL.Func([IDL.Text], [Group], ['query']),
    'getRumor' : IDL.Func([IDL.Nat], [Rumor], ['query']),
    'getUnarchivedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getUnarchivedComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getUnarchivedDiscussions' : IDL.Func([], [IDL.Vec(Discussion)], ['query']),
    'getUnarchivedRumors' : IDL.Func([], [IDL.Vec(Rumor)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'renameGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'restoreArticle' : IDL.Func([IDL.Nat], [], []),
    'restoreComment' : IDL.Func([IDL.Nat], [], []),
    'restoreDiscussion' : IDL.Func([IDL.Nat], [], []),
    'restoreRumor' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchContent' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'members' : IDL.Vec(Member),
            'groups' : IDL.Vec(Group),
            'rumors' : IDL.Vec(Rumor),
            'articles' : IDL.Vec(Article),
            'discussions' : IDL.Vec(Discussion),
          }),
        ],
        ['query'],
      ),
    'updateArticle' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateDiscussion' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateGroup' : IDL.Func([Group], [], []),
    'updateRumor' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Status], [], []),
    'updateRumorStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };