/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LatestArticleTable {
    itemId: bigint;
    itemType: string;
    uploadDate: Time;
}
export interface Article {
    id: bigint;
    title: string;
    content: string;
    date: Time;
    image?: ExternalBlob;
    archived: boolean;
}
export type Time = bigint;
export interface Trending {
    id: bigint;
    contentId: bigint;
    contentType: string;
    timestamp: Time;
}
export interface Discussion {
    id: bigint;
    title: string;
    content: string;
    author: Principal;
    timestamp: Time;
    category: string;
    archived: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Schedule {
    date: Time;
    event: string;
    location: string;
}
export interface GroupNews {
    id: bigint;
    title: string;
    content: string;
    date: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Group {
    schedules: Array<Schedule>;
    members: Array<Member>;
    discography: Discography;
    name: string;
    news: Array<GroupNews>;
    memberCount: bigint;
    baseLocation: string;
    formationDate: Time;
    setlists: Array<Setlist>;
    theaterLocation: string;
}
export interface CreateDiscussionRequest {
    title: string;
    content: string;
    category: string;
}
export interface Discography {
    albums: Array<Album>;
    singles: Array<Single>;
}
export interface Comment {
    id: bigint;
    contentId: bigint;
    content: string;
    author: Principal;
    timestamp: Time;
    archived: boolean;
}
export interface Rumor {
    id: bigint;
    status: Status;
    title: string;
    content: string;
    date: Time;
    archived: boolean;
}
export interface CreateRumorRequest {
    status: Status;
    title: string;
    content: string;
}
export interface Album {
    title: string;
    tracks: Array<string>;
    releaseDate: Time;
}
export interface Single {
    title: string;
    tracks: Array<string>;
    releaseDate: Time;
}
export interface CreateArticleRequest {
    title: string;
    content: string;
    image?: ExternalBlob;
}
export interface TrendingTable {
    itemId: bigint;
    timestamp: Time;
    itemType: string;
}
export interface Setlist {
    title: string;
    tracks: Array<string>;
}
export interface Member {
    bio: string;
    nickname: string;
    birthdate: Time;
    team: string;
    generation: string;
    fullName: string;
}
export interface HomepageContent {
    latestArticlesTable: Array<LatestArticleTable>;
    rumors: Array<Rumor>;
    articles: Array<Article>;
    trending: Array<Trending>;
    discussions: Array<Discussion>;
    trendingTable: Array<TrendingTable>;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Status {
    unconfirm = "unconfirm",
    confirm = "confirm",
    waiting = "waiting"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(contentId: bigint, content: string): Promise<bigint>;
    addTrending(contentId: bigint, contentType: string): Promise<bigint>;
    archiveArticle(id: bigint): Promise<void>;
    archiveComment(id: bigint): Promise<void>;
    archiveDiscussion(id: bigint): Promise<void>;
    archiveRumor(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createArticle(request: CreateArticleRequest): Promise<bigint>;
    createDiscussion(request: CreateDiscussionRequest): Promise<bigint>;
    createGroup(group: Group): Promise<void>;
    createRumor(request: CreateRumorRequest): Promise<bigint>;
    deleteGroup(name: string): Promise<void>;
    filterArticlesByTitle(title: string): Promise<Array<Article>>;
    filterDiscussionsByCategory(category: string): Promise<Array<Discussion>>;
    filterRumorsByStatus(status: Status): Promise<Array<Rumor>>;
    getAllArticles(): Promise<Array<Article>>;
    getAllComments(): Promise<Array<Comment>>;
    getAllDiscussions(): Promise<Array<Discussion>>;
    getAllGroups(): Promise<Array<Group>>;
    getAllRumors(): Promise<Array<Rumor>>;
    getAllTrending(): Promise<Array<Trending>>;
    getArticle(id: bigint): Promise<Article>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComment(id: bigint): Promise<Comment>;
    getCommentsByContentId(contentId: bigint): Promise<Array<Comment>>;
    getDiscussion(id: bigint): Promise<Discussion>;
    getGroup(name: string): Promise<Group>;
    getHomepageContent(): Promise<HomepageContent>;
    getRumor(id: bigint): Promise<Rumor>;
    getTrending(id: bigint): Promise<Trending>;
    getUnarchivedArticles(): Promise<Array<Article>>;
    getUnarchivedComments(): Promise<Array<Comment>>;
    getUnarchivedDiscussions(): Promise<Array<Discussion>>;
    getUnarchivedRumors(): Promise<Array<Rumor>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeTrending(id: bigint): Promise<void>;
    restoreArticle(id: bigint): Promise<void>;
    restoreComment(id: bigint): Promise<void>;
    restoreDiscussion(id: bigint): Promise<void>;
    restoreRumor(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateArticle(id: bigint, title: string, image: ExternalBlob | null, content: string): Promise<void>;
    updateComment(id: bigint, content: string): Promise<void>;
    updateDiscussion(id: bigint, title: string, category: string, content: string): Promise<void>;
    updateGroup(group: Group): Promise<void>;
    updateRumor(id: bigint, title: string, content: string, status: Status): Promise<void>;
}
import type { Article as _Article, CreateArticleRequest as _CreateArticleRequest, CreateRumorRequest as _CreateRumorRequest, Discussion as _Discussion, ExternalBlob as _ExternalBlob, HomepageContent as _HomepageContent, LatestArticleTable as _LatestArticleTable, Rumor as _Rumor, Status as _Status, Time as _Time, Trending as _Trending, TrendingTable as _TrendingTable, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addTrending(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrending(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrending(arg0, arg1);
            return result;
        }
    }
    async archiveArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveArticle(arg0);
            return result;
        }
    }
    async archiveComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveComment(arg0);
            return result;
        }
    }
    async archiveDiscussion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveDiscussion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveDiscussion(arg0);
            return result;
        }
    }
    async archiveRumor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveRumor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveRumor(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createArticle(arg0: CreateArticleRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(await to_candid_CreateArticleRequest_n10(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(await to_candid_CreateArticleRequest_n10(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createDiscussion(arg0: CreateDiscussionRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDiscussion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDiscussion(arg0);
            return result;
        }
    }
    async createGroup(arg0: Group): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0);
            return result;
        }
    }
    async createRumor(arg0: CreateRumorRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRumor(to_candid_CreateRumorRequest_n13(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRumor(to_candid_CreateRumorRequest_n13(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async deleteGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroup(arg0);
            return result;
        }
    }
    async filterArticlesByTitle(arg0: string): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterArticlesByTitle(arg0);
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterArticlesByTitle(arg0);
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async filterDiscussionsByCategory(arg0: string): Promise<Array<Discussion>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterDiscussionsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterDiscussionsByCategory(arg0);
            return result;
        }
    }
    async filterRumorsByStatus(arg0: Status): Promise<Array<Rumor>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterRumorsByStatus(to_candid_Status_n15(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterRumorsByStatus(to_candid_Status_n15(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticles();
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticles();
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllComments(): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComments();
            return result;
        }
    }
    async getAllDiscussions(): Promise<Array<Discussion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDiscussions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDiscussions();
            return result;
        }
    }
    async getAllGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGroups();
            return result;
        }
    }
    async getAllRumors(): Promise<Array<Rumor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRumors();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRumors();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllTrending(): Promise<Array<Trending>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrending();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrending();
            return result;
        }
    }
    async getArticle(arg0: bigint): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_Article_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_Article_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getComment(arg0: bigint): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.getComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComment(arg0);
            return result;
        }
    }
    async getCommentsByContentId(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsByContentId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsByContentId(arg0);
            return result;
        }
    }
    async getDiscussion(arg0: bigint): Promise<Discussion> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscussion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscussion(arg0);
            return result;
        }
    }
    async getGroup(arg0: string): Promise<Group> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroup(arg0);
            return result;
        }
    }
    async getHomepageContent(): Promise<HomepageContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomepageContent();
                return from_candid_HomepageContent_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomepageContent();
            return from_candid_HomepageContent_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRumor(arg0: bigint): Promise<Rumor> {
        if (this.processError) {
            try {
                const result = await this.actor.getRumor(arg0);
                return from_candid_Rumor_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRumor(arg0);
            return from_candid_Rumor_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTrending(arg0: bigint): Promise<Trending> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrending(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrending(arg0);
            return result;
        }
    }
    async getUnarchivedArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnarchivedArticles();
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnarchivedArticles();
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUnarchivedComments(): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnarchivedComments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnarchivedComments();
            return result;
        }
    }
    async getUnarchivedDiscussions(): Promise<Array<Discussion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnarchivedDiscussions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnarchivedDiscussions();
            return result;
        }
    }
    async getUnarchivedRumors(): Promise<Array<Rumor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnarchivedRumors();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnarchivedRumors();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeTrending(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTrending(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTrending(arg0);
            return result;
        }
    }
    async restoreArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreArticle(arg0);
            return result;
        }
    }
    async restoreComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreComment(arg0);
            return result;
        }
    }
    async restoreDiscussion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreDiscussion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreDiscussion(arg0);
            return result;
        }
    }
    async restoreRumor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreRumor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreRumor(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateArticle(arg0: bigint, arg1: string, arg2: ExternalBlob | null, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, arg1, await to_candid_opt_n32(this.uploadFile, this.downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, arg1, await to_candid_opt_n32(this.uploadFile, this.downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateComment(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComment(arg0, arg1);
            return result;
        }
    }
    async updateDiscussion(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDiscussion(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDiscussion(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateGroup(arg0: Group): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGroup(arg0);
            return result;
        }
    }
    async updateRumor(arg0: bigint, arg1: string, arg2: string, arg3: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRumor(arg0, arg1, arg2, to_candid_Status_n15(this.uploadFile, this.downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRumor(arg0, arg1, arg2, to_candid_Status_n15(this.uploadFile, this.downloadFile, arg3));
            return result;
        }
    }
}
async function from_candid_Article_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Promise<Article> {
    return await from_candid_record_n19(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_HomepageContent_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomepageContent): Promise<HomepageContent> {
    return await from_candid_record_n31(uploadFile, downloadFile, value);
}
function from_candid_Rumor_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rumor): Rumor {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_Status_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n26(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
async function from_candid_opt_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    date: _Time;
    image: [] | [_ExternalBlob];
    archived: boolean;
}): Promise<{
    id: bigint;
    title: string;
    content: string;
    date: Time;
    image?: ExternalBlob;
    archived: boolean;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        image: record_opt_to_undefined(await from_candid_opt_n20(uploadFile, downloadFile, value.image)),
        archived: value.archived
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    title: string;
    content: string;
    date: _Time;
    archived: boolean;
}): {
    id: bigint;
    status: Status;
    title: string;
    content: string;
    date: Time;
    archived: boolean;
} {
    return {
        id: value.id,
        status: from_candid_Status_n25(uploadFile, downloadFile, value.status),
        title: value.title,
        content: value.content,
        date: value.date,
        archived: value.archived
    };
}
async function from_candid_record_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latestArticlesTable: Array<_LatestArticleTable>;
    rumors: Array<_Rumor>;
    articles: Array<_Article>;
    trending: Array<_Trending>;
    discussions: Array<_Discussion>;
    trendingTable: Array<_TrendingTable>;
}): Promise<{
    latestArticlesTable: Array<LatestArticleTable>;
    rumors: Array<Rumor>;
    articles: Array<Article>;
    trending: Array<Trending>;
    discussions: Array<Discussion>;
    trendingTable: Array<TrendingTable>;
}> {
    return {
        latestArticlesTable: value.latestArticlesTable,
        rumors: from_candid_vec_n22(uploadFile, downloadFile, value.rumors),
        articles: await from_candid_vec_n17(uploadFile, downloadFile, value.articles),
        trending: value.trending,
        discussions: value.discussions,
        trendingTable: value.trendingTable
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unconfirm: null;
} | {
    confirm: null;
} | {
    waiting: null;
}): Status {
    return "unconfirm" in value ? Status.unconfirm : "confirm" in value ? Status.confirm : "waiting" in value ? Status.waiting : value;
}
function from_candid_variant_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Promise<Array<Article>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Article_n18(uploadFile, downloadFile, x)));
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Rumor>): Array<Rumor> {
    return value.map((x)=>from_candid_Rumor_n23(uploadFile, downloadFile, x));
}
async function to_candid_CreateArticleRequest_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateArticleRequest): Promise<_CreateArticleRequest> {
    return await to_candid_record_n11(uploadFile, downloadFile, value);
}
function to_candid_CreateRumorRequest_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateRumorRequest): _CreateRumorRequest {
    return to_candid_record_n14(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_Status_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n16(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
async function to_candid_opt_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n12(uploadFile, downloadFile, value));
}
async function to_candid_record_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    image?: ExternalBlob;
}): Promise<{
    title: string;
    content: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        title: value.title,
        content: value.content,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n12(uploadFile, downloadFile, value.image)) : candid_none()
    };
}
function to_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    title: string;
    content: string;
}): {
    status: _Status;
    title: string;
    content: string;
} {
    return {
        status: to_candid_Status_n15(uploadFile, downloadFile, value.status),
        title: value.title,
        content: value.content
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    unconfirm: null;
} | {
    confirm: null;
} | {
    waiting: null;
} {
    return value == Status.unconfirm ? {
        unconfirm: null
    } : value == Status.confirm ? {
        confirm: null
    } : value == Status.waiting ? {
        waiting: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
